/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/OIMuRtIKLY0
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuRadioItem, DropdownMenuRadioGroup, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"

export function Component() {
  return (
    (<div className="container mx-auto px-4 md:px-6 py-12">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-3xl font-bold">Modern Products</h1>
          <p className="text-gray-500 dark:text-gray-400">Find the perfect product for your needs</p>
        </div>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button className="shrink-0" variant="outline">
              <ArrowUpDownIcon className="w-4 h-4 mr-2" />
              Sort by
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" className="w-[200px]">
            <DropdownMenuRadioGroup value="featured">
              <DropdownMenuRadioItem value="featured">Featured</DropdownMenuRadioItem>
              <DropdownMenuRadioItem value="newest">Newest</DropdownMenuRadioItem>
              <DropdownMenuRadioItem value="low">Price: Low to High</DropdownMenuRadioItem>
              <DropdownMenuRadioItem value="high">Price: High to Low</DropdownMenuRadioItem>
            </DropdownMenuRadioGroup>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
      <div
        className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
        <div
          className="bg-white dark:bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow">
          <img
            alt="Product Image"
            className="w-full h-60 object-cover"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400} />
          <div className="p-4">
            <h3 className="text-lg font-semibold mb-2">Modern Desk Lamp</h3>
            <div className="flex items-center justify-between">
              <span className="text-gray-900 dark:text-gray-50 font-bold text-xl">$49.99</span>
              <Button size="sm">Add to Cart</Button>
            </div>
          </div>
        </div>
        <div
          className="bg-white dark:bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow">
          <img
            alt="Product Image"
            className="w-full h-60 object-cover"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400} />
          <div className="p-4">
            <h3 className="text-lg font-semibold mb-2">Ergonomic Office Chair</h3>
            <div className="flex items-center justify-between">
              <span className="text-gray-900 dark:text-gray-50 font-bold text-xl">$199.99</span>
              <Button size="sm">Add to Cart</Button>
            </div>
          </div>
        </div>
        <div
          className="bg-white dark:bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow">
          <img
            alt="Product Image"
            className="w-full h-60 object-cover"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400} />
          <div className="p-4">
            <h3 className="text-lg font-semibold mb-2">Wireless Headphones</h3>
            <div className="flex items-center justify-between">
              <span className="text-gray-900 dark:text-gray-50 font-bold text-xl">$99.99</span>
              <Button size="sm">Add to Cart</Button>
            </div>
          </div>
        </div>
        <div
          className="bg-white dark:bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow">
          <img
            alt="Product Image"
            className="w-full h-60 object-cover"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400} />
          <div className="p-4">
            <h3 className="text-lg font-semibold mb-2">Minimalist Wall Clock</h3>
            <div className="flex items-center justify-between">
              <span className="text-gray-900 dark:text-gray-50 font-bold text-xl">$29.99</span>
              <Button size="sm">Add to Cart</Button>
            </div>
          </div>
        </div>
        <div
          className="bg-white dark:bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow">
          <img
            alt="Product Image"
            className="w-full h-60 object-cover"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400} />
          <div className="p-4">
            <h3 className="text-lg font-semibold mb-2">Sleek Desk Organizer</h3>
            <div className="flex items-center justify-between">
              <span className="text-gray-900 dark:text-gray-50 font-bold text-xl">$39.99</span>
              <Button size="sm">Add to Cart</Button>
            </div>
          </div>
        </div>
        <div
          className="bg-white dark:bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow">
          <img
            alt="Product Image"
            className="w-full h-60 object-cover"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400} />
          <div className="p-4">
            <h3 className="text-lg font-semibold mb-2">Wireless Charging Pad</h3>
            <div className="flex items-center justify-between">
              <span className="text-gray-900 dark:text-gray-50 font-bold text-xl">$24.99</span>
              <Button size="sm">Add to Cart</Button>
            </div>
          </div>
        </div>
        <div
          className="bg-white dark:bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow">
          <img
            alt="Product Image"
            className="w-full h-60 object-cover"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400} />
          <div className="p-4">
            <h3 className="text-lg font-semibold mb-2">Bamboo Cutting Board</h3>
            <div className="flex items-center justify-between">
              <span className="text-gray-900 dark:text-gray-50 font-bold text-xl">$19.99</span>
              <Button size="sm">Add to Cart</Button>
            </div>
          </div>
        </div>
        <div
          className="bg-white dark:bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow">
          <img
            alt="Product Image"
            className="w-full h-60 object-cover"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400} />
          <div className="p-4">
            <h3 className="text-lg font-semibold mb-2">Retro Desk Lamp</h3>
            <div className="flex items-center justify-between">
              <span className="text-gray-900 dark:text-gray-50 font-bold text-xl">$59.99</span>
              <Button size="sm">Add to Cart</Button>
            </div>
          </div>
        </div>
      </div>
    </div>)
  );
}

function ArrowUpDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m21 16-4 4-4-4" />
      <path d="M17 20V4" />
      <path d="m3 8 4-4 4 4" />
      <path d="M7 4v16" />
    </svg>)
  );
}
