/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Z2Mc23hD4Sy
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Archivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"

export function Component() {
  return (
    (<div className="container mx-auto py-12 px-4 md:px-6">
      <div className="grid gap-8 md:grid-cols-2">
        <div className="space-y-6">
          <div
            className="flex items-center gap-4 rounded-lg bg-white p-4 shadow-md dark:bg-gray-800">
            <Avatar className="h-16 w-16">
              <AvatarImage alt="@shadcn" src="/placeholder-avatar.jpg" />
              <AvatarFallback>JP</AvatarFallback>
            </Avatar>
            <div className="space-y-1">
              <h2 className="text-2xl font-bold">Jared Palmer</h2>
              <p className="text-gray-500 dark:text-gray-400">jared@acme.com</p>
            </div>
          </div>
          <div className="rounded-lg bg-white p-4 shadow-md dark:bg-gray-800">
            <h3 className="text-lg font-semibold">Sales</h3>
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <img
                    alt="Product Image"
                    className="rounded-md"
                    height={48}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "48/48",
                      objectFit: "cover",
                    }}
                    width={48} />
                  <div>
                    <h4 className="font-medium">Acme Desk Lamp</h4>
                    <p className="text-sm text-gray-500 dark:text-gray-400">$99.99</p>
                  </div>
                </div>
                <p className="text-sm text-gray-500 dark:text-gray-400">May 15, 2023</p>
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <img
                    alt="Product Image"
                    className="rounded-md"
                    height={48}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "48/48",
                      objectFit: "cover",
                    }}
                    width={48} />
                  <div>
                    <h4 className="font-medium">Acme Ergonomic Chair</h4>
                    <p className="text-sm text-gray-500 dark:text-gray-400">$249.99</p>
                  </div>
                </div>
                <p className="text-sm text-gray-500 dark:text-gray-400">April 20, 2023</p>
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <img
                    alt="Product Image"
                    className="rounded-md"
                    height={48}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "48/48",
                      objectFit: "cover",
                    }}
                    width={48} />
                  <div>
                    <h4 className="font-medium">Acme Wireless Keyboard</h4>
                    <p className="text-sm text-gray-500 dark:text-gray-400">$59.99</p>
                  </div>
                </div>
                <p className="text-sm text-gray-500 dark:text-gray-400">March 10, 2023</p>
              </div>
            </div>
          </div>
        </div>
        <div className="space-y-6">
          <div className="rounded-lg bg-white p-4 shadow-md dark:bg-gray-800">
            <h3 className="text-lg font-semibold">Pets</h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="flex flex-col items-center gap-2">
                <img
                  alt="Pet Image"
                  className="rounded-full"
                  height={100}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "100/100",
                    objectFit: "cover",
                  }}
                  width={100} />
                <div className="text-center">
                  <h4 className="font-medium">Buddy</h4>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Dog</p>
                </div>
              </div>
              <div className="flex flex-col items-center gap-2">
                <img
                  alt="Pet Image"
                  className="rounded-full"
                  height={100}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "100/100",
                    objectFit: "cover",
                  }}
                  width={100} />
                <div className="text-center">
                  <h4 className="font-medium">Whiskers</h4>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Cat</p>
                </div>
              </div>
              <div className="flex flex-col items-center gap-2">
                <img
                  alt="Pet Image"
                  className="rounded-full"
                  height={100}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "100/100",
                    objectFit: "cover",
                  }}
                  width={100} />
                <div className="text-center">
                  <h4 className="font-medium">Chirpy</h4>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Bird</p>
                </div>
              </div>
              <div className="flex flex-col items-center gap-2">
                <img
                  alt="Pet Image"
                  className="rounded-full"
                  height={100}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "100/100",
                    objectFit: "cover",
                  }}
                  width={100} />
                <div className="text-center">
                  <h4 className="font-medium">Nibbles</h4>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Hamster</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>)
  );
}
